### ISSUE TITLE
Simply visually awesome your Home Assistant configuration

### ISSUE THREAD

**Issue by jirmjos** [Petro31/home-assistant-config#15]
Huge thanks for sharing.

Hunting for long time (maybe from one year ago) a implemented HA like yours, but never found nothing enough well build and visually as good your Lovelace customization.
I want replicate most of your configuration aproach, but I dont have not enough deep knowledge HA to understand all you implemented to Lovelace customization and mainly all your scripts to launch all main tasks.
I´m not a software developer as you can easily imagine, and I´m in the hardware layer working in IT from more than 30 years, but still learning first steps in software development.
I´m day by day studing your config and little step by step I undertand better.
Best regards.

Very sorry about hickjaking with this message your github, of course you can delete this "fake issue" I posted, but I cannot find other good way to send you this.

**Comment by Petro31** [comment]
@jirmjos do you have any questions?  Github really didn't notify me and I somehow missed this issue til now.
