### ISSUE TITLE
Why you banning people for stating that HA should be apolitical?

### ISSUE THREAD

**Issue by cracrama** [Petro31/home-assistant-config#28]
Why you banning people for stating that HA should be apolitical? Is this official HA creator stance?

**Comment by Petro31** [comment]
Politics aren't allowed on the HA media platforms.  Sorry, I didn't make the rule.

**Comment by cracrama** [comment]
Is this a statement? , or response to the question? If this is a statement, then it completelly contradicts your actions. You in fact banned people who were asking that platform should stay away from politics. People have been banned for exactly this kind of request and their account marked as "troll accounts" - Is this official HA policy?  So you want to make impression of "appoliticall" platform  but same time  making decisions based  politics? And you trying to silience people?

**Comment by Petro31** [comment]
Dude, read the HA code of conduct.  Go bother someone else.  My github repo has nothing to do with whatever issue you have with me.

**Comment by cracrama** [comment]
Seems like you're pretending that you don't understand the question. You in fact have banned people who were asking that platform should stay away from politics. Now you claiming that it was other way around and hiding behind "harrasment" So it  seems like  it's very "creative" use of "code of conduct".

**Comment by poudenes** [comment]
Can we all keep focus on coding here on github. Sorry guys but this discussion isn't here on right place to do.

Sorry for this post.
