### ISSUE TITLE
Question re: groups

### ISSUE THREAD

**Issue by johntdyer** [Petro31/home-assistant-config#29]
Hello,  

Thank you for sharing your config, its very helpful and inspiring !   I did have a question re: groups.yaml though if you have a second...

https://github.com/Petro31/home-assistant-config/blob/6c779f2573aa6057cddb2de32a1f4c13e9e61672/group.yaml#L5-L7

you mention that this is deprecated but your comment on its replacement isnt exactly clear to me... I often find myself strugging with groups and that fact that you can compose groups of groups is kinda mind blowing to me :)

**Comment by Petro31** [comment]
Sorry, didn't catch this message until now.  I have no clue what I'm saying there.  My goal is to move to the interface when there's an easy way to iterate areas with templates.  There is now, I just haven't moved that direction yet.
